apiVersion: apps/v1
kind: Deployment
metadata:
  name: salescart-pod
  namespace: salescart-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: salescart
  template:
    metadata:
      labels:
        app: salescart
    spec:
      containers:
        - name: salescart-api
          resources:
            limits:
              cpu: "2000m"
            requests:
              cpu: "1000m"
