apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/salescart-pod/
patchesStrategicMerge:
- ./kind-salescart-patch.yaml
images:
- name: salescart-api-image
  newName: salescart-api-amd64
  newTag: "1.0"
